name: Actualizar precio del aceite

on:
  schedule:
    - cron: '0 6 * * *'  # Ejecutar todos los días a las 06:00 UTC
  workflow_dispatch:     # También se puede ejecutar manualmente

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar script scraper.py
        run: python scraper.py

      - name: Confirmar y subir cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin
          git reset --soft origin/main
          git add precio-aceite.json
          git commit -m "Actualizar precio automáticamente"
          git push
